### PR TITLE
fix: report when subcommand is missing

### LINKED ISSUE #518: [sda-cli] command exits with panic when just the `-config CONFIGFILE` is provided
**Describe the bug**

When the command is run with 
```sh
sda-cli -config <CONFIGFILE> 
```
It exits with panic and showing errors like
```
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
main.ParseArgs()
	/data3/work/BILS/project/project-sda/sda-cli/main.go:137 +0x5d8
main.main()
	/data3/work/BILS/project/project-sda/sda-cli/main.go:73 +0x38
```

**Steps to reproduce**

**Expected behavior**
- [ ] 
It should show more user friendly message such as 
`Error: sub command is missing`. 

**Additional context**

**Estimation of size**: small

**Estimation of priority**: low

### PR DESCRIPTION
**Pull request by MalinAhlberg**
**Related issue(s) and PR(s)**  
This PR closes #518 .

**Description**
```
$./sda-cli -config s3cfg 
Error: no command given
```
Note that the term "command" is used, rather than "subcommand", as this is the term we consistently use in the help section:

>  /sda-cli -config s3cfg  help
> Usage: sda-cli [-config <config-file>] <**command**> [OPTIONS]
> 
> A tool for common tasks with the Sensitive Data Archive (SDA)
> 
> **Commands**:
>   createKey   Creates a Crypt4GH key pair
> ...
> 
> Run 'sda-cli help <**command**>' for more information on a command.

**How to test**
Run `sda-cli --config myconfigfil`.
All other commands should work as previously.

### CODE REVIEW

File: main.go [hunk 1]
```diff
@@ -134,6 +134,11 @@ func ParseArgs() (string, []string, string) {
 
 	// Extract the command from the 1st argument, then remove it
 	// from list of arguments.
+	if len(os.Args) < 2 {
+		fmt.Fprintf(os.Stderr, "Error: no command given\n")
+		os.Exit(1)
+
```
Comment (nanjiangshu) [inline main.go:140]:
```suggestion
```

**Review by nanjiangshu — APPROVED** [review]
Looks good! Just remove the extra empty line.

**Review by jbygdell — APPROVED** [review]
